# Backend
backend = "glx";      # Use "xrender" if glx causes issues or you have older hardware
vsync = true;

# GLX specific settings

# Window types
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
};

